---

- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"
  tags:
    - always

- name: Include optional user and group creation.
  include_tasks: kibana-optional-user.yml
  when: (kibana_group is defined) and (kibana_user is defined)

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# This will always run

- name: Enabling kibana service upon boot & restarting
  debug: msg="Finished installing Kibana. Reloading systemd config & Restarting"
  notify:
    - reload systemd configuration
    - restart kibana
  changed_when: True

